### ISSUE TITLE
HTML Special characters

### ISSUE THREAD

**Issue by martoio** [klhall1987/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/
The ampersand should be written as:
``&amp;``

https://github.com/klhall1987/prj-rev-bwfs-dasmoto/blob/bfcc6797619255023825624fd748c073bb5512ff/dasmoto/index.html#L5

**Comment by klhall1987** [comment]
Fixed in new upload
