### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [klhall1987/prj-rev-bwfs-dasmoto#3]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/klhall1987/prj-rev-bwfs-dasmoto/blob/bfcc6797619255023825624fd748c073bb5512ff/dasmoto/index.html#L14

**Comment by klhall1987** [comment]
@martoio I'm pretty sure all the images had alt tags. I know they weren't very specific, but I figured since this was a practice project, I would just make it something super simple. In the future I'll make them more detailed.
