### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by martoio** [klhall1987/prj-rev-bwfs-dasmoto#4]
Make sure you implement proper indentation in your code to ease readability and show any parent-child relationships between the elements.
https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/
https://github.com/klhall1987/prj-rev-bwfs-dasmoto/blob/bfcc6797619255023825624fd748c073bb5512ff/dasmoto/index.html#L8-L9

**Comment by klhall1987** [comment]
Fixed in new upload.
