### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by martoio** [klhall1987/prj-rev-bwfs-dasmoto#5]
You can put the ``font-family`` on the ``html`` or ``body`` elements, that way you don't have to constantly specify the font for all the elements:

https://github.com/klhall1987/prj-rev-bwfs-dasmoto/blob/bfcc6797619255023825624fd748c073bb5512ff/dasmoto/assets/css/style.css#L2

**Comment by klhall1987** [comment]
If I'm not mistaken the reason I did it that way was because the spec sheet didn't indicate that all sections needed Helvetica. So I didn't want to override all the outputs with that font family.
